//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ASDNotificationCenterDialogObserver_Protocol_h
#define ASDNotificationCenterDialogObserver_Protocol_h

@import Foundation;

@protocol ASDNotificationCenterDialogObserver <NSObject>

@required

/* required instance methods */
- (void)handleAuthenticateRequest:(id)_authenticateRequest resultHandler:(id /* block */)_handler;
- (void)handleDialogRequest:(id)_dialogRequest resultHandler:(id /* block */)_handler;

@optional

/* optional instance methods */
- (void)handleEngagementRequest:(id)_engagementRequest resultHandler:(id /* block */)_handler;
- (void)handlePurchase:(id)_purchase resultHandler:(id /* block */)_handler;
- (void)handleViewPresentationRequest:(id)_viewPresentationRequest resultHandler:(id /* block */)_handler;

@end

#endif /* ASDNotificationCenterDialogObserver_Protocol_h */
