//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKBookFetchCoverImageOperation_h
#define CKBookFetchCoverImageOperation_h

@import AppKit;

#include "CKBook.h"
#include "ISOperation.h"

@interface CKBookFetchCoverImageOperation : ISOperation

@property (readonly) CKBook *book;
@property (readonly) NSImage *coverImage;

/* instance methods */
- (void)run;
- (id)_downloadCoverImageFromURL:(id)_coverImageFromURL returningError:(id *)_error;
- (id)initWithBook:(id)_book storeClient:(id)_client;

@end

#endif /* CKBookFetchCoverImageOperation_h */
