//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKBook_h
#define CKBook_h

@import Foundation;

#include "SSPurchase.h"

@interface CKBook : NSObject <NSCopying, NSSecureCoding>

@property (retain) NSMutableDictionary *externalMetadata;
@property (copy) NSURL *coverImageURL;
@property (copy) NSNumber *jaliscoItemIdentifier;
@property (copy) NSString *path;
@property signed char isLocal;
@property (copy) NSString *title;
@property (copy) NSString *author;
@property (copy) NSString *category;
@property (copy) NSString *sortName;
@property (copy) NSDate *purchaseDate;
@property (copy) NSString *uniqueIdentifier;
@property (copy, nonatomic) NSNumber *itemIdentifier;
@property (copy) NSNumber *publicationVersion;
@property (copy) NSString *publicationDisplayVersion;
@property (copy) NSDictionary *bookInfo;
@property (copy) NSDictionary *iTunesMetaData;
@property (copy) NSString *redownloadBuyParams;
@property (copy) NSNumber *downloadAssetSize;
@property (copy) NSString *updateBuyParams;
@property (readonly) SSPurchase *redownloadPurchase;
@property (readonly) SSPurchase *updatePurchase;
@property (readonly) signed char isPreorder;
@property (copy) NSDate *expectedReleaseDate;
@property (copy) NSNumber *daapPurchasedToken;
@property (copy) NSNumber *daapItemIdentifier;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)_imageFetchQueue;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)valueForUndefinedKey:(id)_forUndefinedKey;
- (void)setValue:(id)_value forUndefinedKey:(id)_undefinedKey;
- (void)_copyLibraryPropertiesFromBook:(id)_libraryPropertiesFromBook;
- (void)fetchCoverImageWithCompletionHandler:(id /* block */)_coverImageWithCompletionHandler;
- (id)getItemIdentifier;
- (signed char)isEqualToBook:(id)_equalToBook;

@end

#endif /* CKBook_h */
