//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKDAAPPurchasedItem_h
#define CKDAAPPurchasedItem_h

@import Foundation;

#include "CKBook.h"

@interface CKDAAPPurchasedItem : CKBook <NSSecureCoding>

@property (copy) NSDictionary *daapDictionary;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;

@end

#endif /* CKDAAPPurchasedItem_h */
