//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKDockMessaging_h
#define CKDockMessaging_h

@import Foundation;

@interface CKDockMessaging : NSObject {
    /* instance variables */
    NSObject<OS_xpc_object> *_xpcDockConnection;
    NSMutableDictionary *_cachedIconPaths;
}

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (id)_xpcDispatchQueue;
- (id)_xpcDockConnection;
- (id)cachedIconPathForProductID:(id)_iconPathForProductID;
- (void)loadIconForIdentifier:(id)_iconForIdentifier fromURL:(id)_url storeClient:(id)_client;
- (void)loadIconForProductID:(id)_iconForProductID fromURL:(id)_url storeClient:(id)_client;
- (void)loadIconForProductWithInfo:(id)_info storeClient:(id)_client;
- (void)sendDockMessage:(int)_dockMessage;
- (void)sendInitialMessageForDownload:(id)_initialMessageForDownload;
- (void)sendInitialMessageForProductID:(id)_initialMessageForProductID title:(id)_title bundleID:(id)_id action:(int)_action flyOrigin:(CGRect)_origin imagePath:(id)_path;
- (void)sendMessageForDownload:(id)_messageForDownload status:(id)_status;
- (id)xpcObjectForDownload:(id)_download status:(id)_status;
- (id)xpcProgressObjectWithType:(int)_progressObjectWithType productID:(const char *)_id title:(const char *)_title bundleID:(const char *)_id imagePath:(const char *)_path status:(int)_status progress:(double)_progress installPath:(const char *)_path downloadedBytes:(double)_bytes totalBytes:(double)_bytes;

@end

#endif /* CKDockMessaging_h */
