//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKLocalization_h
#define CKLocalization_h

@import Foundation;

@interface CKLocalization : NSObject

@end

#endif /* CKLocalization_h */
