//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKRootHelper_h
#define CKRootHelper_h

@import Foundation;

@interface CKRootHelper : NSObject {
    /* instance variables */
    NSXPCConnection *_connection;
    NSLock *_connectionLock;
}

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (id)_connection;
- (id)proxy;

@end

#endif /* CKRootHelper_h */
