//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKSoftwareProduct_h
#define CKSoftwareProduct_h

@import Foundation;

@interface CKSoftwareProduct : NSObject <NSSecureCoding, NSCopying>

@property (retain) NSString *accountOpaqueDSID;
@property (retain) NSString *accountIdentifier;
@property (retain) NSString *appName;
@property (retain) NSString *bundleIdentifier;
@property (retain) NSString *bundleVersion;
@property (retain) NSString *bundlePath;
@property (retain) NSString *receiptType;
@property (retain) NSNumber *itemIdentifier;
@property (retain) NSNumber *storeFrontIdentifier;
@property (retain) NSNumber *versionIdentifier;
@property (retain) NSDate *purchaseDate;
@property (retain) NSValue *mdItemRef;
@property signed char installed;
@property long long source;
@property signed char isVPPLicensed;
@property signed char vppLicenseRevoked;
@property (retain) NSString *vppLicenseOrganizationName;
@property (retain) NSDate *vppLicenseExpirationDate;
@property (retain) NSDate *vppLicenseRenewalDate;
@property (retain) NSString *vppLicenseCancellationReason;
@property signed char isMachineLicensed;
@property signed char isLegacyApp;
@property signed char metadataChangeIsExpected;
@property signed char metadataChangeHasAlreadyOccurred;
@property (copy) NSString *expectedBundleVersion;
@property (copy) NSNumber *expectedStoreVersion;
@property (readonly) NSString *sourceString;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)createSoftwareProductForAppAtPath:(id)_softwareProductForAppAtPath;
+ (id)productPathToUpgradeForBundleIdentifier:(id)_pathToUpgradeForBundleIdentifier versionNumberString:(id)_numberString;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;

@end

#endif /* CKSoftwareProduct_h */
