//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKSoftwareUpdateStatus_h
#define CKSoftwareUpdateStatus_h

@import Foundation;

@interface CKSoftwareUpdateStatus : NSObject <NSSecureCoding>

@property (readonly, nonatomic) long long state;
@property (readonly, nonatomic) unsigned long long bytesDownloaded;
@property (readonly, nonatomic) unsigned long long bytesTotal;
@property (readonly, nonatomic) double percentComplete;
@property (readonly, nonatomic) double estimatedTimeRemaining;
@property (readonly, nonatomic) signed char canCancel;
@property (readonly, nonatomic) NSError *error;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithError:(id)_error;
- (id)initWithProgress:(double)_progress statusInfo:(id)_info canCancel:(signed char)_cancel;

@end

#endif /* CKSoftwareUpdateStatus_h */
