//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKUpdate_h
#define CKUpdate_h

@import Foundation;

#include "SSPurchase.h"

@interface CKUpdate : NSObject <NSSecureCoding>

@property (readonly) NSDictionary *dictionary;
@property (readonly, nonatomic) NSNumber *itemIdentifier;
@property (readonly, nonatomic) NSString *actionParams;
@property (readonly, nonatomic) NSString *bundleID;
@property (readonly, nonatomic) NSString *bundleVersion;
@property (readonly, nonatomic) NSDate *releaseDate;
@property (readonly, nonatomic) NSString *title;
@property (nonatomic) signed char isStaged;
@property (readonly, nonatomic) SSPurchase *purchase;
@property (nonatomic) long long softwareUpdateState;
@property (nonatomic) long long autoUpdateAbortCode;
@property (readonly, nonatomic) NSString *autoUpdateAbortReason;
@property (readonly, nonatomic) signed char didFailToAutoInstall;
@property (nonatomic) signed char hasBeenSeenByUser;
@property (copy, nonatomic) NSDate *firstAutoUpdateAttemptDate;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithDictionary:(id)_dictionary;
- (double)_autoInstallUpdateMaximumRetryInterval;

@end

#endif /* CKUpdate_h */
