//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAccountStoreObserver_Protocol_h
#define ISAccountStoreObserver_Protocol_h

@protocol ISAccountStoreObserver

@required

/* required instance methods */
- (void)primaryAccountDidChange:(id)_accountDidChange;

@optional

@end

#endif /* ISAccountStoreObserver_Protocol_h */
