//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAppleIDLookupOperation_h
#define ISAppleIDLookupOperation_h

@import Foundation;

#include "ISOperation.h"
#include "ISURLOperationDelegate-Protocol.h"

@class ISPurchaseReceipt; // @import CommerceCore;

@interface ISAppleIDLookupOperation : ISOperation <ISURLOperationDelegate> {
    /* instance variables */
    ISPurchaseReceipt *mReceipt;
    NSString *mAppleID;
}

@property (readonly) NSString *appleID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)appleIDLookupOperationForReceipt:(id)_idlookupOperationForReceipt storeClient:(id)_client;

/* instance methods */
- (void)run;
- (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;
- (id)_newURLOperationWithURLBagType:(unsigned long long)_urlbagType;
- (id)_requestBodyData;
- (id)initWithReceipt:(id)_receipt storeClient:(id)_client;

@end

#endif /* ISAppleIDLookupOperation_h */
