//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAuthenticationContext_h
#define ISAuthenticationContext_h

@import Foundation;

@interface ISAuthenticationContext : NSObject <NSSecureCoding> {
    /* instance variables */
    long long _style;
}

@property signed char demoMode;
@property signed char demoAutologinMode;
@property (retain) NSString *demoAccountName;
@property (retain) NSString *demoAccountPassword;
@property (readonly) NSNumber *accountID;
@property (retain) NSDictionary *additionalQueryParameters;
@property long long authenticationStyle;
@property long long authenticationReason;
@property long long bagType;
@property (retain) NSDictionary *signUpQueryParameters;
@property signed char shouldFollowAccountButtons;
@property signed char useCachedCredentials;
@property (retain) NSString *appleIDOverride;
@property signed char enforceAppleIDOverride;
@property (retain) NSString *applicationName;
@property (retain) NSDictionary *dialogDictionary;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithAccountID:(id)_accountID;

@end

#endif /* ISAuthenticationContext_h */
