//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAuthenticationResponse_h
#define ISAuthenticationResponse_h

@import Foundation;

@interface ISAuthenticationResponse : NSObject <NSSecureCoding> {
    /* instance variables */
    unsigned long long _urlBagType;
}

@property unsigned long long URLBagType;
@property (readonly) NSString *accountIdentifier;
@property (readonly) long long accountKind;
@property (readonly) NSString *creditString;
@property (readonly) NSNumber *dsID;
@property (readonly) NSString *token;
@property (readonly) NSString *storeFront;
@property (readonly) signed char isManagedStudent;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithDictionary:(id)_dictionary;
- (signed char)_loadFromDictionary:(id)_fromDictionary;

@end

#endif /* ISAuthenticationResponse_h */
