//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAuthenticationChallenge_h
#define ISAuthenticationChallenge_h

@import Foundation;

@interface ISAuthenticationChallenge : NSObject

@property (retain) NSString *localizedMessage;
@property (retain) NSString *localizedTitle;
@property (readonly) signed char hasPassword;
@property (readonly) NSString *password;
@property (readonly) NSString *user;
@property (readonly) long long failureCount;
@property (readonly) signed char userNameIsEditable;
@property (readonly) signed char userNameIsEmail;
@property (readonly, weak) id <NSURLAuthenticationChallengeSender> sender;

/* instance methods */
- (void)cancelAuthentication;
- (void)useCredential:(id)_credential;

@end

#endif /* ISAuthenticationChallenge_h */
