//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISAvailableUpdatesObserver_Protocol_h
#define ISAvailableUpdatesObserver_Protocol_h

@protocol ISAvailableUpdatesObserver

@required

/* required instance methods */
- (void)availableUpdatesDidChangedWithUpdates:(id)_updatesDidChangedWithUpdates osUpdates:(id)_updates badgeCount:(unsigned long long)_count;

@optional

@end

#endif /* ISAvailableUpdatesObserver_Protocol_h */
