//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISCodeSignatureOperation_h
#define ISCodeSignatureOperation_h

@import Foundation;

#include "ISOperation.h"
#include "ISServiceProxy.h"

@interface ISCodeSignatureOperation : ISOperation

@property (retain) ISServiceProxy *proxy;
@property (retain) NSString *bundlePath;
@property signed char showProgress;
@property signed char isDeveloperSigned;
@property signed char isAppleSigned;

/* class methods */
+ (id)operationWithBundlePath:(id)_withBundlePath showProgress:(signed char)_progress storeClient:(id)_client;

/* instance methods */
- (void)main;
- (id)initWithBundlePath:(id)_bundlePath showProgress:(signed char)_progress storeClient:(id)_client;

@end

#endif /* ISCodeSignatureOperation_h */
