//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDevice_h
#define ISDevice_h

@import Foundation;

@interface ISDevice : NSObject

/* class methods */
+ (id)guid;
+ (signed char)isTouchIDCapable;
+ (long long)availableDiskSpace;
+ (id)eosDeviceType;
+ (long long)availableSpaceOnDiskAtPath:(id)_spaceOnDiskAtPath;
+ (signed char)hasTouchIDAndEnrolled;
+ (signed char)isBootedFromRecoveryPartition;
+ (id)osMajorVersionString;
+ (void)osVersionReturningMajor:(int *)_versionReturningMajor minor:(int *)_minor point:(int *)_point;

@end

#endif /* ISDevice_h */
