//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDelayedInvocationRecorder_h
#define ISDelayedInvocationRecorder_h

#include "ISInvocationRecorder.h"

@interface ISDelayedInvocationRecorder : ISInvocationRecorder

@property (nonatomic) double delayInterval;

/* instance methods */
- (void)invokeInvocation:(id)_invocation;

@end

#endif /* ISDelayedInvocationRecorder_h */
