//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialogDelegateProxy_h
#define ISDialogDelegateProxy_h

@import Foundation;

#include "ISDialogDelegate-Protocol.h"

@protocol OS_dispatch_queue; // @import Dispatch;

@interface ISDialogDelegateProxy : NSObject <ISDialogDelegate>

@property (retain) id <ISDialogDelegate> delegate;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *requestQueue;

/* instance methods */
- (id)initWithDelegate:(id)_delegate;
- (void)dialog:(id)_dialog shouldDismissWithReturnCode:(long long)_dismissWithReturnCode replyBlock:(id /* block */)_block;

@end

#endif /* ISDialogDelegateProxy_h */
