//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialogButton_h
#define ISDialogButton_h

@import Foundation;

@interface ISDialogButton : NSObject <NSSecureCoding>

@property int actionType;
@property (retain) id parameter;
@property (retain) NSString *title;
@property (retain) NSNumber *state;
@property long long urlType;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)buttonWithTitle:(id)_withTitle;

/* instance methods */
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (int)_actionTypeForString:(id)_typeForString;
- (long long)_urlTypeForString:(id)_typeForString;
- (signed char)isEqual:(id)_equal superficial:(signed char)_superficial;
- (void)loadFromDictionary:(id)_dictionary;
- (void)performActionFromDialog:(id)_actionFromDialog withStoreClient:(id)_storeClient;
- (void)performActionWithStoreClient:(id)_actionWithStoreClient;

@end

#endif /* ISDialogButton_h */
