//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialogOperation_h
#define ISDialogOperation_h

@import Foundation;

#include "ISDialog.h"
#include "ISDialogButton.h"
#include "ISDialogOperationDelegate-Protocol.h"
#include "ISOperation.h"
#include "ISServerAuthenticationOperation.h"

@interface ISDialogOperation : ISOperation <ISDialogOperationDelegate> {
    /* instance variables */
    id _userNotification;
}

@property (readonly) ISServerAuthenticationOperation *authenticationOperation;
@property (readonly) ISDialog *dialog;
@property signed char performDefaultActions;
@property (retain) ISDialogButton *selectedButton;
@property (readonly) NSNumber *authenticatedAccountDSID;
@property (copy) id /* block */ buttonClickHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)operationWithDialog:(id)_withDialog storeClient:(id)_client;

/* instance methods */
- (id)init;
- (void)run;
- (void)handleButtonSelected:(long long)_buttonSelected;
- (id)initWithDialog:(id)_dialog storeClient:(id)_client;
- (void)operation:(id)_operation selectedButton:(id)_button;

@end

#endif /* ISDialogOperation_h */
