//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialogTextField_h
#define ISDialogTextField_h

@import Foundation;

@interface ISDialogTextField : NSObject

@property long long keyboardType;
@property signed char secure;
@property (retain) NSString *title;
@property (retain) NSString *value;

/* class methods */
+ (id)textFieldWithTitle:(id)_title;

/* instance methods */
- (signed char)isSecure;

@end

#endif /* ISDialogTextField_h */
