//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialogDelegate_Protocol_h
#define ISDialogDelegate_Protocol_h

@protocol ISDialogDelegate

@required

/* required instance methods */
- (void)dialog:(id)_dialog shouldDismissWithReturnCode:(long long)_dismissWithReturnCode replyBlock:(id /* block */)_block;

@optional

@end

#endif /* ISDialogDelegate_Protocol_h */
