//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDialog_h
#define ISDialog_h

@import Foundation;

#include "ISDialogButton.h"
#include "ISDialogDelegate-Protocol.h"

@interface ISDialog : NSObject <NSSecureCoding> {
    /* instance variables */
    NSLock *_lock;
    NSMutableDictionary *_userInfo;
}

@property (readonly) ISDialogButton *okButton;
@property (readonly) ISDialogButton *cancelButton;
@property (readonly) ISDialogButton *otherButton;
@property (readonly) ISDialogButton *suppressionCheckbox;
@property (readonly) NSDictionary *baseDictionary;
@property (retain) NSArray *buttons;
@property long long defaultButtonIndex;
@property signed char oneButtonPerLine;
@property signed char groupsTextFields;
@property (retain) NSArray *textFields;
@property (retain) NSString *message;
@property (retain) NSString *title;
@property signed char allowDuplicates;
@property signed char authorizationIsForced;
@property signed char dismissOnLock;
@property signed char expectsResponse;
@property long long kind;
@property (readonly) NSDictionary *authenticationParameters;
@property (readonly) signed char needsDedicatedUI;
@property (weak, nonatomic) id <ISDialogDelegate> delegate;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)dialogWithError:(id)_withError;
+ (id)dialogWithDictionary:(id)_withDictionary;
+ (void)dismissDialogWithDictionary:(id)_dialogWithDictionary;

/* instance methods */
- (id)init;
- (signed char)isEqual:(id)_equal;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (void)beginSheetModalForWindow:(id)_sheetModalForWindow completionHandler:(id /* block */)_handler;
- (id)initWithError:(id)_error;
- (void)performAction:(long long)_action;
- (id)initWithTitle:(id)_title message:(id)_message;
- (long long)_kindForString:(id)_forString;
- (id)initWithAuthenticationChallege:(id)_authenticationChallege;
- (id)_appWindow;
- (id)_bundleForStoreClient:(id)_forStoreClient authenticationReason:(long long)_reason;
- (void)_gotoFollowUpURL:(id)_followUpURL;
- (void)_runModalWithSettings:(id)_settings completionHandler:(id /* block */)_handler;
- (id)copyUserNotification;
- (void)dismissDialogWithExitCode:(long long)_dialogWithExitCode;
- (void)handleDismissNoficiation:(id)_dismissNoficiation;
- (id)initWithDialogDictionary:(id)_dialogDictionary;
- (void)setValue:(id)_value forUserInfoKey:(id)_userInfoKey;
- (signed char)shouldDismissWithReturnCode:(long long)_dismissWithReturnCode userInfo:(id *)_info;
- (void)stopModalForDialog:(id)_modalForDialog;
- (id)valueForUserInfoKey:(id)_forUserInfoKey;

@end

#endif /* ISDialog_h */
