//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDownloadQueueObserver_Protocol_h
#define ISDownloadQueueObserver_Protocol_h

@protocol ISDownloadQueueObserver

@required

/* required instance methods */
- (void)download:(id)_download didUpdateStatus:(id)_updateStatus;
- (void)downloadQueueDidAddDownload:(id)_queueDidAddDownload;
- (void)downloadQueueDidCheckServerDownloadQueueForAccount:(id)_queueDidCheckServerDownloadQueueForAccount withDownloadCount:(long long)_downloadCount newDownloads:(id)_downloads;
- (void)downloadQueueDidRemoveDownload:(id)_queueDidRemoveDownload queueIsIdle:(signed char)_isIdle;

@optional

@end

#endif /* ISDownloadQueueObserver_Protocol_h */
