//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISDownloadService_Protocol_h
#define ISDownloadService_Protocol_h

#include "ISServiceRemoteObject-Protocol.h"

@protocol ISDownloadService <ISServiceRemoteObject>

@required

/* required instance methods */
- (void)addDownloadQueueObserver:(id)_downloadQueueObserver reply:(id /* block */)_reply;
- (void)addDownload:(id)_download replyBlock:(id /* block */)_block;
- (void)cacheReceiptAsString:(id)_receiptAsString forDownload:(id)_download reply:(id /* block */)_reply;
- (void)cancelDownloadWithItemIdentifier:(unsigned long long)_downloadWithItemIdentifier promptToConfirm:(signed char)_toConfirm askToDelete:(signed char)_toDelete;
- (void)checkServerDownloadQueueWithReplyBlock:(id /* block */)_serverDownloadQueueWithReplyBlock;
- (void)checkStoreDownloadQueueForAccount:(id)_storeDownloadQueueForAccount;
- (void)downloadWithItemIdentifier:(unsigned long long)_withItemIdentifier reply:(id /* block */)_reply;
- (void)downloadsWithTypeMask:(long long)_withTypeMask reply:(id /* block */)_reply;
- (void)fetchIconForItemIdentifier:(unsigned long long)_iconForItemIdentifier atURL:(id)_url replyBlock:(id /* block */)_block;
- (void)lockApplicationsForBundleID:(id)_applicationsForBundleID;
- (void)lockedApplicationTriedToLaunchAtPath:(id)_applicationTriedToLaunchAtPath;
- (void)pauseDownloadWithItemIdentifier:(unsigned long long)_downloadWithItemIdentifier;
- (void)performedIconAnimationForDownloadWithIdentifier:(unsigned long long)_iconAnimationForDownloadWithIdentifier;
- (void)removeDownloadQueueObserver:(id)_downloadQueueObserver;
- (void)removeDownloadWithItemIdentifier:(unsigned long long)_downloadWithItemIdentifier;
- (void)restoreDownloadsWithArchivedFiles:(id)_downloadsWithArchivedFiles replyBlock:(id /* block */)_block;
- (void)resumeDownloadWithItemIdentifier:(unsigned long long)_downloadWithItemIdentifier;
- (void)unlockApplicationsWithBundleIdentifier:(id)_applicationsWithBundleIdentifier;
- (void)triggerDownloadsWithReplyBlock:(id /* block */)_downloadsWithReplyBlock;
- (void)checkAutomaticDownloadQueue;
- (void)checkPreflightWithItemIdentifier:(unsigned long long)_preflightWithItemIdentifier url:(id)_url systemVersionInfo:(id)_versionInfo replyBlock:(id /* block */)_block;
- (void)performDownload:(id)_download withOptions:(unsigned long long)_options replyBlock:(id /* block */)_block;
- (void)resetStatusForDownloadWithItemIdentifier:(unsigned long long)_statusForDownloadWithItemIdentifier;
- (void)runErrorDialogForDownloadMetadata:(id)_downloadMetadata error:(id)_error;
- (void)runWarningDialogForDownloadMetadata:(id)_downloadMetadata error:(id)_error replyBlock:(id /* block */)_block;

@optional

@end

#endif /* ISDownloadService_Protocol_h */
