//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISFetchIconOperation_h
#define ISFetchIconOperation_h

@import Foundation;

#include "ISOperation.h"

@interface ISFetchIconOperation : ISOperation {
    /* instance variables */
    NSURL *_remoteURL;
    NSURL *_localURL;
    NSURL *_localIconURL;
}

@property (readonly) NSNumber *productID;
@property (readonly) NSURL *iconURL;

/* instance methods */
- (void)run;
- (id)initWithProductID:(id)_productID url:(id)_url storeClient:(id)_client;

@end

#endif /* ISFetchIconOperation_h */
