//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISInvocationRecorder_h
#define ISInvocationRecorder_h

@import Foundation;

@interface ISInvocationRecorder : NSObject {
    /* instance variables */
    id _target;
}

/* instance methods */
- (void)dealloc;
- (void)forwardInvocation:(id)_invocation;
- (id)methodSignatureForSelector:(SEL)_signatureForSelector;
- (id)initWithTarget:(id)_target;
- (id)adjustedTargetForSelector:(SEL)_targetForSelector;
- (void)invokeInvocation:(id)_invocation;

@end

#endif /* ISInvocationRecorder_h */
