//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISMainThreadInvocationRecorder_h
#define ISMainThreadInvocationRecorder_h

#include "ISInvocationRecorder.h"

@interface ISMainThreadInvocationRecorder : ISInvocationRecorder

@property (nonatomic) signed char waitUntilDone;

/* instance methods */
- (void)invokeInvocation:(id)_invocation;

@end

#endif /* ISMainThreadInvocationRecorder_h */
