//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISManagedRestrictions_h
#define ISManagedRestrictions_h

@import Foundation;

@interface ISManagedRestrictions : NSObject

/* class methods */
+ (signed char)isRestrictedTo:(struct __CFString *)_restrictedTo;

@end

#endif /* ISManagedRestrictions_h */
