//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOperation_h
#define ISOperation_h

@import Foundation;

#include "ISOperationDelegate-Protocol.h"
#include "ISServiceProxy.h"
#include "ISStoreAccount.h"
#include "ISStoreClient.h"
#include "SSOperationProgress.h"

@interface ISOperation : NSOperation {
    /* instance variables */
    NSLock *_lock;
    NSLock *_serviceProxyLock;
    NSLock *_storeAccountLock;
}

@property (retain) NSRunLoop *operationRunLoop;
@property (retain) ISOperation *subOperation;
@property (readonly, nonatomic) SSOperationProgress *progress;
@property (retain) ISOperation *parentOperation;
@property (weak) id <ISOperationDelegate> delegate;
@property (readonly) ISServiceProxy *serviceProxy;
@property (retain) ISStoreClient *storeClient;
@property (retain, nonatomic) ISStoreAccount *storeAccount;
@property void * operationContext;
@property (readonly) NSString *uniqueKey;
@property (readonly) id xpcReplyObject;
@property (retain) NSError *error;
@property signed char success;
@property (readonly) long long progressWeight;
@property (readonly) double earlyTimeRemainingEstimate;
@property (copy) id /* block */ completionHandler;
@property (copy) id /* block */ progressHandler;
@property int requiredBagType;

/* instance methods */
- (id)init;
- (void)run;
- (void)lock;
- (void)unlock;
- (void)cancel;
- (void)main;
- (void)run:(signed char)_run;
- (id)initWithStoreClient:(id)_storeClient;
- (signed char)runSubOperation:(id)_subOperation returningError:(id *)_error;
- (void)_sendErrorToDelegate:(id)_errorToDelegate;
- (void)_sendSuccessToDelegate;
- (void)_failAfterException;
- (signed char)_loadRequredBagReturningError:(id *)_requredBagReturningError;
- (void)_main:(signed char)__main;
- (int)runRunLoopUntilStopped;
- (signed char)runSyncReturningError:(id *)_syncReturningError;
- (void)sendProgressToDelegate;
- (signed char)showDialogInSeperateProcessForOperation:(id)_dialogInSeperateProcessForOperation;
- (void)stopRunLoop;
- (id)urlForURLBagKey:(id)_urlbagKey;
- (id)urlForURLBagKey:(id)_urlbagKey dsID:(id)_id;
- (id)valueForURLBagKey:(id)_forURLBagKey;
- (id)valueForURLBagKey:(id)_forURLBagKey dsID:(id)_id;

@end

#endif /* ISOperation_h */
