//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOperationQueue_h
#define ISOperationQueue_h

@import Foundation;

@interface ISOperationQueue : NSObject {
    /* instance variables */
    NSOperationQueue *_queue;
}

/* class methods */
+ (id)mainQueue;
+ (signed char)isActive;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)addOperation:(id)_operation;
- (void)setMaxConcurrentOperationCount:(long long)_maxConcurrentOperationCount;
- (void)cancelAllOperations;
- (id)operations;
- (void)setSuspended:(signed char)_suspended;

@end

#endif /* ISOperationQueue_h */
