//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOperationDelegate_Protocol_h
#define ISOperationDelegate_Protocol_h

@import Foundation;

@protocol ISOperationDelegate <NSObject>

@required

@optional

/* optional instance methods */
- (void)operation:(id)_operation failedWithError:(id)_withError;
- (void)operationFinished:(id)_finished;
- (void)operation:(id)_operation updatedProgress:(id)_progress;

@end

#endif /* ISOperationDelegate_Protocol_h */
