//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOSUpdateProgressObserver_Protocol_h
#define ISOSUpdateProgressObserver_Protocol_h

@protocol ISOSUpdateProgressObserver

@required

/* required instance methods */
- (void)osUpdates:(id)_updates changedProgress:(id)_progress;

@optional

@end

#endif /* ISOSUpdateProgressObserver_Protocol_h */
