//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOSUpdateScanObserver_Protocol_h
#define ISOSUpdateScanObserver_Protocol_h

@protocol ISOSUpdateScanObserver

@required

/* required instance methods */
- (void)osUpdateScanForTags:(id)_updateScanForTags didProgressWithPercentComplete:(float)_progressWithPercentComplete isFinished:(signed char)_finished error:(id)_error;

@optional

@end

#endif /* ISOSUpdateScanObserver_Protocol_h */
