//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISPropertyListProvider_h
#define ISPropertyListProvider_h

@import Foundation;

#include "ISDataProvider.h"
#include "ISOperationDelegate-Protocol.h"
#include "ISServiceProxy.h"

@interface ISPropertyListProvider : ISDataProvider <ISOperationDelegate> {
    /* instance variables */
    signed char _shouldRedirectOnGotoAction;
}

@property (readonly) ISServiceProxy *serviceProxy;
@property signed char shouldProcessAccount;
@property signed char shouldProcessDialogs;
@property (readonly) signed char didProcessDialog;
@property signed char shouldProcessProtocol;
@property signed char shouldProcessDownloads;
@property signed char shouldProcessDownloadsForUpToDate;
@property (readonly) NSArray *upToDateDownloadItemIDs;
@property signed char shouldTriggerDownloads;
@property (copy) id /* block */ actionHandler;
@property (copy) id /* block */ gotoActionHandler;
@property (retain) NSString *touchIDChallenge;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithStoreClient:(id)_storeClient;
- (signed char)processPropertyList:(id)_propertyList returningError:(id *)_error;
- (void)_processActions:(id)_actions fallback:(id)_fallback;
- (void)_processDownloads:(id)_downloads fallback:(id)_fallback;
- (void)_processPingsInDictionary:(id)_pingsInDictionary;
- (signed char)_processStoreVersion:(id)_storeVersion returningError:(id *)_error;
- (void)_processTriggerDownload:(id)_triggerDownload fallback:(id)_fallback;
- (void)operation:(id)_operation selectedButton:(id)_button;
- (signed char)parseData:(id)_data returningError:(id *)_error;
- (signed char)processDialogFromPropertyList:(id)_dialogFromPropertyList returningError:(id *)_error;

@end

#endif /* ISPropertyListProvider_h */
