//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISServiceClientInterface_h
#define ISServiceClientInterface_h

@import Foundation;

#include "ISServiceDelegate.h"
#include "ISServiceProxy.h"
#include "ISServiceRemoteObject-Protocol.h"

@protocol OS_dispatch_queue; // @import Dispatch;

@interface ISServiceClientInterface : ISServiceProxy <ISServiceRemoteObject> {
    /* instance variables */
    NSLock *_serviceProxyLock;
}

@property (readonly) NSXPCConnection *conn;
@property (weak) ISServiceDelegate *delegate;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *requestQueue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithConnection:(id)_connection delegate:(id)_delegate;
- (id)primaryAccount;
- (void)startService;
- (void)setStoreFrontID:(id)_storeFrontID;
- (id)accountWithDSID:(id)_withDSID;
- (signed char)authIsExpired;
- (signed char)copyAccountID:(id *)_accountID byAuthenticatingWithContext:(id)_authenticatingWithContext returningError:(id *)_error;
- (void)displayDialog:(id)_dialog;
- (id)exportedObjectInterface;
- (id)exportedObjectProtocol;
- (id)httpHeadersForURL:(id)_headersForURL withDSID:(id)_dsid;
- (signed char)loadURLBagWithType:(long long)_type returningError:(id *)_error;
- (id)remoteObjectProtocol;
- (signed char)shouldSendGUIDWithRequestForURL:(id)_sendGUIDWithRequestForURL;
- (void)signURLRequest:(id)_urlrequest service:(id)_service;
- (id)storeURLSchemeForAmbiguousURL:(id)_urlschemeForAmbiguousURL;
- (id)urlForURLBagKey:(id)_urlbagKey;
- (signed char)urlIsTrustedByURLBag:(id)_isTrustedByURLBag;
- (id)valueForURLBagKey:(id)_forURLBagKey;

@end

#endif /* ISServiceClientInterface_h */
