//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISServiceDelegate_h
#define ISServiceDelegate_h

@import Foundation;

@interface ISServiceDelegate : NSObject <NSXPCListenerDelegate> {
    /* instance variables */
    NSLock *_clientsLock;
    NSString *_serviceName;
}

@property (readonly) NSArray *clients;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedInstance;
+ (Class)clientInterfaceClass;

/* instance methods */
- (id)init;
- (signed char)listener:(id)_listener shouldAcceptNewConnection:(id)_acceptNewConnection;
- (id)initWithServiceName:(id)_serviceName;
- (void)client:(id)_client didInterruptConnection:(id)_interruptConnection;
- (void)client:(id)_client didInvalidationConnection:(id)_invalidationConnection;

@end

#endif /* ISServiceDelegate_h */
