//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISSignInPrompt_h
#define ISSignInPrompt_h

@import AppKit;
@import Foundation;

#include "ISAuthenticationContext.h"
#include "ISDialog.h"
#include "ISStoreClient.h"

@interface ISSignInPrompt : NSWindowController {
    /* instance variables */
    NSTextField *titleField;
    NSTextField *messageField;
    NSImageView *imageView;
    NSButton *defaultButton;
    NSButton *otherButton;
    NSButton *alternateButton;
    NSButton *forgotButton;
    NSButton *helpButton;
    NSProgressIndicator *progressIndicator;
    NSTextField *usernameField;
    NSTextField *passwordField;
    NSTextField *errorField;
    CGRect windowFactoryFrame;
    CGRect titleFieldFactoryFrame;
    CGRect defaultButtonFactoryFrame;
    NSString *mSuppressionCheckboxTitle;
    NSNumber *mSuppressionCheckboxState;
    signed char mForceActivate;
    long long attempts;
    long long mExitCode;
}

@property (retain, nonatomic) NSString *username;
@property (retain, nonatomic) NSString *suppressionCheckboxTitle;
@property (retain, nonatomic) NSNumber *suppressionCheckboxState;
@property signed char forceActivate;
@property (readonly) NSString *password;
@property (readonly) id authentication;
@property (retain, nonatomic) NSURL *authenticateAccountURL;
@property (retain, nonatomic) ISAuthenticationContext *context;
@property (retain, nonatomic) ISStoreClient *storeClient;
@property (retain, nonatomic) ISDialog *dialog;
@property (retain, nonatomic) NSWindow *sheetWindow;
@property signed char usernameFieldIsEnabled;

/* instance methods */
- (void)setOtherButtonTitle:(id)_otherButtonTitle;
- (void)_prepare;
- (void)awakeFromNib;
- (void)controlTextDidChange:(id)_textDidChange;
- (void)setDefaultButtonTitle:(id)_defaultButtonTitle;
- (void)setAlternateButtonTitle:(id)_alternateButtonTitle;
- (void)setTitleString:(id)_titleString;
- (void)alternateButtonAction:(id)_buttonAction;
- (void)_dismissPanelWithCode:(long long)_panelWithCode;
- (void)forgotPassword:(id)_password;
- (void)_alertSheetDidDismiss:(id)_sheetDidDismiss returnCode:(long long)_code contextInfo:(void *)_info;
- (void)_alertSheetDidEnd:(id)_sheetDidEnd returnCode:(long long)_code contextInfo:(void *)_info;
- (void)_beginAuthDialogWithCompletionHandler:(id /* block */)_authDialogWithCompletionHandler;
- (void)_beginDialogWithCompletionHandler:(id /* block */)_dialogWithCompletionHandler;
- (id)_customIconImage;
- (void)_handleError:(id)_error returnCode:(long long)_code;
- (void)_hideProgressIndicator;
- (void)_prepareAK:(id)_ak;
- (void)_setButtonState:(id)_buttonState withString:(id)_string;
- (void)_showError:(id)_error;
- (void)_showProgressIndicator:(id)_progressIndicator;
- (void)beginDialogWithCompletionHandler:(id /* block */)_dialogWithCompletionHandler;
- (void)defaultButtonAction:(id)_buttonAction;
- (void)helpButtonAction:(id)_buttonAction;
- (id)initWithDialog:(id)_dialog storeClient:(id)_client;
- (void)otherButtonAction:(id)_buttonAction;
- (void)setMessageString:(id)_messageString;

@end

#endif /* ISSignInPrompt_h */
