//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISSingleton_Protocol_h
#define ISSingleton_Protocol_h

@import Foundation;

@protocol ISSingleton <NSObject>

@required

/* class methods */
+ (id)sharedInstance;

@optional

@end

#endif /* ISSingleton_Protocol_h */
