//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISSignInPromptSettings_h
#define ISSignInPromptSettings_h

@import AppKit;
@import Foundation;

#include "ISAuthenticationContext.h"
#include "ISStoreClient.h"

@interface ISSignInPromptSettings : NSObject <NSSecureCoding>

@property (retain) NSString *titleString;
@property (retain) NSString *messageString;
@property (retain) NSString *defaultButtonString;
@property (retain) NSString *alternateButtonString;
@property (retain) NSString *otherButtonString;
@property (retain) NSString *suppressionCheckboxString;
@property (retain) NSNumber *suppressionCheckboxState;
@property (retain) NSURL *authenticateAccountURL;
@property (retain) NSWindow *sheetWindow;
@property (retain) ISAuthenticationContext *context;
@property (retain) ISStoreClient *storeClient;
@property signed char needsDedicatedUI;
@property signed char shouldUseAppStoreUI;
@property signed char forceActivate;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)settingsWithTitle:(id)_withTitle message:(id)_message defaultButton:(id)_button alternateButton:(id)_button otherButton:(id)_button suppressionCheckbox:(id)_checkbox suppressionCheckboxState:(id)_checkboxState authenticateAccountURL:(id)_accountURL authenticationContext:(id)_context needsDedicatedUI:(signed char)_dedicatedUI storeClient:(id)_client;
+ (id)settingsWithTitle:(id)_withTitle message:(id)_message defaultButton:(id)_button alternateButton:(id)_button otherButton:(id)_button suppressionCheckbox:(id)_checkbox suppressionCheckboxState:(id)_checkboxState authenticateAccountURL:(id)_accountURL authenticationContext:(id)_context shouldUseAppStoreUI:(signed char)_useAppStoreUI storeClient:(id)_client;
+ (id)settingsWithTitle:(id)_withTitle message:(id)_message defaultButton:(id)_button alternateButton:(id)_button otherButton:(id)_button suppressionCheckbox:(id)_checkbox suppressionCheckboxState:(id)_checkboxState authenticateAccountURL:(id)_accountURL authenticationContext:(id)_context storeClient:(id)_client;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)_shortDescriptionForString:(id)_descriptionForString;

@end

#endif /* ISSignInPromptSettings_h */
