//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISSoftwareMapObserver_Protocol_h
#define ISSoftwareMapObserver_Protocol_h

@protocol ISSoftwareMapObserver

@required

/* required instance methods */
- (void)softwareProduct:(id)_product updatedState:(long long)_state;

@optional

@end

#endif /* ISSoftwareMapObserver_Protocol_h */
