//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISStoreAuthenticationChallenge_h
#define ISStoreAuthenticationChallenge_h

@import Foundation;

#include "ISAuthenticationChallenge.h"

@interface ISStoreAuthenticationChallenge : ISAuthenticationChallenge

@property long long failureCount;
@property signed char hasPassword;
@property (retain) NSString *password;
@property (weak) id <NSURLAuthenticationChallengeSender> sender;
@property (retain) NSString *user;
@property signed char userNameIsEditable;

/* instance methods */
- (id)init;
- (signed char)userNameIsEmail;

@end

#endif /* ISStoreAuthenticationChallenge_h */
