//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISStoreAccount_h
#define ISStoreAccount_h

@import Foundation;

@interface ISStoreAccount : NSObject <NSSecureCoding> {
    /* instance variables */
    NSTimer *_tokenInvalidTimer;
}

@property long long touchIDState;
@property (copy) NSNumber *dsID;
@property (copy) NSString *identifier;
@property long long kind;
@property (copy) NSString *creditString;
@property (retain) NSString *storeFront;
@property signed char isSignedIn;
@property signed char isManagedStudent;
@property (copy) NSString *password;
@property (copy) NSString *token;
@property (readonly) signed char authenticated;
@property long long URLBagType;
@property (retain) NSDate *tokenIssuedDate;
@property (retain) NSTimer *tokenExpirationTimer;
@property (readonly) signed char primary;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)dsidFromPlistValue:(id)_plistValue;
+ (id)migratePersistedStoreDictionary:(id)_persistedStoreDictionary;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (signed char)isAuthenticated;
- (signed char)isPrimary;
- (long long)getTouchIDState;
- (signed char)hasValidStrongToken;
- (id)initWithPersistedStoreDictionary:(id)_persistedStoreDictionary;
- (void)mergeValuesFromAuthenticationResponse:(id)_valuesFromAuthenticationResponse;
- (id)persistedStoreDictionary;
- (void)resetTouchIDState;
- (double)strongTokenValidForSecond;

@end

#endif /* ISStoreAccount_h */
