//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISStoreURLOperation_h
#define ISStoreURLOperation_h

@import Foundation;

#include "ISAuthenticationContext.h"
#include "ISOperationDelegate-Protocol.h"
#include "ISURLOperation.h"
#include "ISURLOperationDelegate-Protocol.h"

@protocol ISStoreURLOperationDelegate;

@interface ISStoreURLOperation : ISURLOperation {
    /* instance variables */
    int _bagType;
    signed char _adiActionInResponse;
    long long _adiSilentActionRetryCount;
}

@property (weak) id <ISStoreURLOperationDelegate, ISURLOperationDelegate, ISOperationDelegate> delegate;
@property (retain) NSString *urlBagKey;
@property (retain) NSNumber *authenticatedDSID;
@property signed char urlKnownToBeTrusted;
@property (retain) ISAuthenticationContext *authenticationContext;
@property signed char needsAuthentication;
@property signed char sendToken;
@property signed char useDSIDSpecificBag;
@property (copy) id /* block */ authenticationCompletedHandler;
@property (copy) id /* block */ requestMutationHandler;
@property signed char shouldRetryOnSilentADIAction;
@property (copy, nonatomic) NSString *strongToken;

/* class methods */
+ (id)acceptLanguageHeaderString;
+ (void)addITunesStoreHeadersToRequest:(id)_itunesStoreHeadersToRequest withStoreClient:(id)_storeClient storeAccount:(id)_account;
+ (void)addStandardQueryParametersForURL:(id)_url request:(id *)_request serviceProxy:(id)_proxy;
+ (id)cacheBusterString;
+ (id)pingOperationWithUrl:(id)_url storeClient:(id)_client;
+ (id)propertyListOperationWithURLBagKey:(id)_listOperationWithURLBagKey storeClient:(id)_client;

/* instance methods */
- (id)description;
- (id)init;
- (void)run;
- (void)handleResponse:(id)_response;
- (signed char)handleRedirectFromDataProvider:(id)_redirectFromDataProvider;
- (void)_addStandardQueryParametersForURL:(id)_standardQueryParametersForURL;
- (signed char)_authenticateReturningError:(id *)_returningError;
- (signed char)_canSendTokenToURL:(id)_sendTokenToURL;
- (signed char)_dataProviderDidProcessDialog;
- (void)_runURLOperation;
- (id)authenticatedAccountDSID;
- (id)newRequestWithURL:(id)_requestWithURL;
- (signed char)shouldFollowRedirectWithRequest:(id)_followRedirectWithRequest returningError:(id *)_error;

@end

#endif /* ISStoreURLOperation_h */
