//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISURLRequest_h
#define ISURLRequest_h

@import Foundation;

@interface ISURLRequest : NSObject <NSSecureCoding, NSCopying> {
    /* instance variables */
    NSArray *_urls;
}

@property (retain) NSData *body;
@property (retain) NSString *method;
@property (retain) NSDictionary *queryStringDictionary;
@property (readonly) NSURL *primaryURL;
@property (retain) NSArray *URLs;
@property double timeoutInterval;
@property signed char retryAfterTimeout;
@property (readonly) signed char resourceRequest;
@property unsigned long long cachePolicy;
@property signed char preventsIdleSystemSleep;
@property signed char suppressADIHeaders;
@property (retain) NSDictionary *customHeaders;
@property signed char alwaysSendGUID;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)requestWithURL:(id)_withURL;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (id)init;
- (signed char)isEqual:(id)_equal;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithURL:(id)_url;
- (void)setValue:(id)_value forHeaderField:(id)_headerField;
- (id)initWithURLRequest:(id)_urlrequest;
- (id)newURLRequestWithURL:(id)_url storeAccount:(id)_account serviceProxy:(id)_proxy;
- (void)setValue:(id)_value forQueryStringParameter:(id)_queryStringParameter;

@end

#endif /* ISURLRequest_h */
