//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISURLOperationDelegate_Protocol_h
#define ISURLOperationDelegate_Protocol_h

#include "ISOperationDelegate-Protocol.h"

@protocol ISURLOperationDelegate <ISOperationDelegate>

@required

@optional

/* optional instance methods */
- (void)operation:(id)_operation didReceiveResponse:(id)_receiveResponse;
- (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;
- (void)operation:(id)_operation willSendRequest:(id)_sendRequest;

@end

#endif /* ISURLOperationDelegate_Protocol_h */
