//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISURLAuthenticationChallenge_h
#define ISURLAuthenticationChallenge_h

@import Foundation;

#include "ISAuthenticationChallenge.h"

@interface ISURLAuthenticationChallenge : ISAuthenticationChallenge {
    /* instance variables */
    NSURLAuthenticationChallenge *_challenge;
}

/* instance methods */
- (void)dealloc;
- (id)password;
- (id)user;
- (id)sender;
- (signed char)hasPassword;
- (long long)failureCount;
- (void)cancelAuthentication;
- (id)initWithAuthenticationChallenge:(id)_authenticationChallenge;
- (void)useCredential:(id)_credential;

@end

#endif /* ISURLAuthenticationChallenge_h */
