//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISURLBagObserver_Protocol_h
#define ISURLBagObserver_Protocol_h

@protocol ISURLBagObserver

@required

/* required instance methods */
- (void)urlBagDidUpdateWithSuccess:(signed char)_bagDidUpdateWithSuccess error:(id)_error;

@optional

@end

#endif /* ISURLBagObserver_Protocol_h */
