//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISUserNotification_h
#define ISUserNotification_h

@import Foundation;

@interface ISUserNotification : NSObject

@property (retain) NSDictionary *dictionary;
@property unsigned long long optionFlags;
@property long long allowedRetryCount;
@property long long currentRetryCount;
@property (retain) NSDictionary *userInfo;

/* instance methods */
- (id)init;
- (struct __CFUserNotification *)copyUserNotification;
- (id)initWithDictionary:(id)_dictionary options:(unsigned long long)_options;

@end

#endif /* ISUserNotification_h */
