//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSBundle_CommerceKit_h
#define NSBundle_CommerceKit_h

@interface NSBundle (CommerceKit)

/* class methods */
+ (id)commerceKit;

@end

#endif /* NSBundle_CommerceKit_h */
