//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSData_SSDebug_h
#define NSData_SSDebug_h

@interface NSData (SSDebug)

/* class methods */
+ (id)dataForNVRAMKey:(id)_forNVRAMKey;
+ (id)dataWithAuthorizationRef:(struct AuthorizationOpaqueRef *)_authorizationRef;

/* instance methods */
- (id)dictionaryFromData;
- (id)hexAddressDescription;
- (id)nvramDescription;

@end

#endif /* NSData_SSDebug_h */
