//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSDictionary_ISPropertyListAdditions_h
#define NSDictionary_ISPropertyListAdditions_h

@interface NSDictionary (ISPropertyListAdditions)

/* instance methods */
- (signed char)shouldTriggerDownloadQueueCheck;

@end

#endif /* NSDictionary_ISPropertyListAdditions_h */
