//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSFileManager_ISAdditions_h
#define NSFileManager_ISAdditions_h

@interface NSFileManager (ISAdditions)

/* class methods */
+ (signed char)_storeMovePath:(id)_movePath toPath:(id)_path;
+ (id)cacheDirectoryPathWithName:(id)_directoryPathWithName;
+ (signed char)ensureDirectoryExists:(id)_directoryExists;
+ (signed char)ensureDirectoryExists:(id)_directoryExists attributes:(id)_attributes;

/* instance methods */
- (signed char)_isFileSignedAtPath:(id)_fileSignedAtPath withRequirement:(struct __CFData *)_requirement basicCheck:(signed char)_check progressHandler:(id /* block */)_handler;
- (signed char)_isFileSignedAtPath:(id)_fileSignedAtPath withRequirement:(struct __CFData *)_requirement;
- (signed char)_isFileSignedAtPath:(id)_fileSignedAtPath withRequirement:(struct __CFData *)_requirement basicCheck:(signed char)_check;
- (signed char)isAppStoreAppAtPath:(id)_appStoreAppAtPath;
- (signed char)isBootableVolume:(id)_bootableVolume;
- (signed char)isInstallableAtPath:(id)_installableAtPath;
- (signed char)isSignedByAppleFileAtPath:(id)_signedByAppleFileAtPath;
- (signed char)isSignedByAppleFileAtPath:(id)_signedByAppleFileAtPath basicCheck:(signed char)_check;
- (signed char)isSignedByAppleFileAtPath:(id)_signedByAppleFileAtPath basicCheck:(signed char)_check progressHandler:(id /* block */)_handler;
- (signed char)isSignedByAppleFileAtPath:(id)_signedByAppleFileAtPath withProgressHandler:(id /* block */)_progressHandler;
- (signed char)isSignedByDeveloperFileAtPath:(id)_signedByDeveloperFileAtPath;
- (signed char)isSignedByDeveloperFileAtPath:(id)_signedByDeveloperFileAtPath basicCheck:(signed char)_check;
- (signed char)isSignedByDeveloperFileAtPath:(id)_signedByDeveloperFileAtPath basicCheck:(signed char)_check progressHandler:(id /* block */)_handler;
- (signed char)isSignedByDeveloperFileAtPath:(id)_signedByDeveloperFileAtPath withProgressHandler:(id /* block */)_progressHandler;
- (signed char)isSignedFileAtPath:(id)_signedFileAtPath;
- (signed char)isUpdatableAtPath:(id)_updatableAtPath;
- (signed char)writeReceiptString:(id)_receiptString toPath:(id)_path;

@end

#endif /* NSFileManager_ISAdditions_h */
