//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSHTTPURLResponse_ISAdditions_h
#define NSHTTPURLResponse_ISAdditions_h

@interface NSHTTPURLResponse (ISAdditions)

/* instance methods */
- (id)expirationDate;
- (double)expirationInterval;
- (signed char)_getCacheControlMaxAge:(double *)_cacheControlMaxAge;
- (signed char)getAppleMaxAge:(double *)_appleMaxAge;
- (id)_dateFromExpires;
- (long long)maxExpectedContentLength;

@end

#endif /* NSHTTPURLResponse_ISAdditions_h */
