//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSNumber_SSAdditions_h
#define NSNumber_SSAdditions_h

@interface NSNumber (SSAdditions)

/* class methods */
+ (id)numberWithItemIdentifier:(unsigned long long)_withItemIdentifier;

/* instance methods */
- (id)initWithItemIdentifier:(unsigned long long)_itemIdentifier;
- (unsigned long long)itemIdentifierValue;

@end

#endif /* NSNumber_SSAdditions_h */
