//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSObject_ISInvocationAdditions_h
#define NSObject_ISInvocationAdditions_h

@interface NSObject (ISInvocationAdditions)

/* instance methods */
- (id)mainThreadProxy;
- (id)blockingMainThreadProxy;
- (id)delayedProxy:(double)_proxy;

@end

#endif /* NSObject_ISInvocationAdditions_h */
