//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSString_ISAdditions_h
#define NSString_ISAdditions_h

@interface NSString (ISAdditions)

/* class methods */
+ (id)uniqueIdentifier;

/* instance methods */
- (id)volumePath;
- (id)copyUTF8StringOfLength:(unsigned long long)_utf8StringOfLength;
- (id)dataFromHexString;
- (unsigned long long)itemIdentifierValue;
- (id)parameterStringByAppendingParameters:(id)_stringByAppendingParameters;
- (id)stringByExpandingTildeInPathOutsideOfSandbox;
- (id)stripPassword;

@end

#endif /* NSString_ISAdditions_h */
