//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSURLResponse_ISAdditions_h
#define NSURLResponse_ISAdditions_h

@interface NSURLResponse (ISAdditions)

/* instance methods */
- (int)statusCode;
- (id)allHeaderFields;

@end

#endif /* NSURLResponse_ISAdditions_h */
