//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSURL_ISAdditions_h
#define NSURL_ISAdditions_h

@interface NSURL (ISAdditions)

/* class methods */
+ (signed char)openURL:(id)_url;
+ (id)_preferredLanguageCode;
+ (id)copyDictionaryForQueryString:(id)_dictionaryForQueryString unescapedValues:(signed char)_values;
+ (id)queryStringForDictionary:(id)_stringForDictionary escapedValues:(signed char)_values;
+ (id)_userVisibleWebKitVersionString;
+ (id)_macOSXBuildString;
+ (id)_macOSXVersionString;
+ (id)escapedStringForString:(id)_stringForString;
+ (id)macOSXVersionString;
+ (id)storeUserAgentStringForClient:(id)_userAgentStringForClient;
+ (id)unescapedStringForString:(id)_stringForString;

/* instance methods */
- (id)urlByAddingStringToQueryString:(id)_byAddingStringToQueryString;
- (id)URLByAppendingQueryDictionary:(id)_urlbyAppendingQueryDictionary;
- (id)dictionaryForQueryStringWithUnescapedValues:(signed char)_forQueryStringWithUnescapedValues;
- (signed char)isSafeExternalURL;
- (id)schemeSwizzledURL;
- (id)stripPassword;
- (id)urlByConvertingToStoreURLForClient:(id)_client;
- (id)urlBySettingQueryStringDictionary:(id)_bySettingQueryStringDictionary;

@end

#endif /* NSURL_ISAdditions_h */
