//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSDownloadManifestResponse_h
#define SSDownloadManifestResponse_h

@import Foundation;

@interface SSDownloadManifestResponse : NSObject <NSCoding>

@property (retain) NSArray *invalidDownloads;
@property (retain) NSArray *validDownloads;

/* instance methods */
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;

@end

#endif /* SSDownloadManifestResponse_h */
