//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSDownloadAsset_h
#define SSDownloadAsset_h

@import Foundation;

@interface SSDownloadAsset : NSObject <NSSecureCoding> {
    /* instance variables */
    NSString *_downloadFolderName;
    signed char _isExternal;
    NSLock *_lock;
    NSURLRequest *_urlRequest;
}

@property long long type;
@property (retain) NSURLRequest *URLRequest;
@property (retain) NSString *downloadFileName;
@property (readonly) NSString *downloadPath;
@property (retain) NSString *processedPath;
@property (retain) NSString *finalizedFileName;
@property (readonly) NSString *finalizedPath;
@property signed char external;
@property long long hashAlgorithm;
@property (retain) NSArray *hashes;
@property (retain) NSArray *clearHashes;
@property long long numberOfBytesToHash;
@property long long subType;
@property long long fileSize;
@property (retain) NSString *customDownloadPath;
@property signed char useUniqueDownloadFolder;
@property signed char skipInstallPhase;
@property (copy) NSString *bundleIdentifier;
@property (copy) NSString *bundleVersion;
@property (retain) NSDictionary *deltaPackage;
@property signed char deltaUpdateFailed;
@property signed char localDeltaUpdateFailed;
@property long long localFullPackageFailureCount;
@property (retain) NSError *localCachingError;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)assetWithURL:(id)_withURL type:(long long)_type;

/* instance methods */
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (signed char)isExternal;
- (id)downloadFolderName;
- (id)initWithURLRequest:(id)_urlrequest type:(long long)_type;
- (void)setDownloadFolderName:(id)_downloadFolderName;
- (void)setLocalFileNameFromBase:(id)_localFileNameFromBase;

@end

#endif /* SSDownloadAsset_h */
