//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSLogManager_h
#define SSLogManager_h

@import Foundation;

@interface SSLogManager : NSObject

/* class methods */
+ (id)sharedManager;
+ (id)dateFormatter;
+ (id)dateFormatterForFilename;
+ (signed char)useSyslog;

/* instance methods */
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line withFormat:(id)_format;
- (id)_createLogFileWithName:(id)_logFileWithName andExtension:(id)_extension;
- (void)_markEnd;
- (void)_markStart;
- (void)_sendAuxiliaryFileToASL:(id)_auxiliaryFileToASL withName:(id)_name;
- (void)_sendStringToOSLog:(id)_stringToOSLog withLevel:(long long)_level;
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line forData:(id)_data toFilename:(id)_filename;
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line forPlist:(id)_plist toFilename:(id)_filename;
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line forRequest:(id)_request toFilename:(id)_filename;
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line forResponse:(id)_response toFilename:(id)_filename;
- (void)logLevel:(unsigned long long)_level inFunction:(const char *)_function inFile:(const char *)_file atLine:(unsigned long long)_line withString:(id)_string;
- (void)manageAppStoreLogOrder:(id)_appStoreLogOrder;
- (void)manageAppStoreLogs:(id)_appStoreLogs withPath:(id)_path;

@end

#endif /* SSLogManager_h */
