//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSRequest_h
#define SSRequest_h

@import Foundation;

@protocol SSRequestDelegate;

@interface SSRequest : NSObject {
    /* instance variables */
    long long _state;
    NSValue *_callbackID;
}

@property (weak, nonatomic) id <SSRequestDelegate> delegate;
@property (readonly) NSString *requestQueueSelectorName;
@property (readonly) NSString *identifier;

/* class methods */
+ (id)_newIdentifier;

/* instance methods */
- (void)dealloc;
- (id)init;
- (signed char)start;
- (void)cancel;
- (id)messageName;
- (signed char)send;
- (void)_failWithError:(id)_withError;
- (id)requestInfo;
- (void)_finish;
- (signed char)issueRequestForIdentifier:(id)_requestForIdentifier error:(id *)_error;
- (void)callback:(id)_callback connectionIsValid:(signed char)_isValid;
- (void)handleDaemonExit;
- (signed char)handleFinishResponse:(id)_finishResponse error:(id *)_error;

@end

#endif /* SSRequest_h */
